name: Test and Build
on: pull_request

jobs:
  test-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: 'true'

      - name: Use Node.js 20.x
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"

      - name: Install and Test OpenSCD
        run: |
          npm ci
          npm run-script build
          cd packages/compas-open-scd
          npm run-script test
